name: CD

on:
  push:
    branches: ["main"]

concurrency:
  group: "deploy-${{ github.ref }}"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - name: Check lint
        run: npm run lint
      - name: Tests
        run: npm run test:coverage
      - name: Build
        run: npm run clean && npm run build
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: echo "::add-mask::${{ secrets.S3_URL }}" && npm run deploy
