name: CI

on:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  check-pr:
    runs-on: ubuntu-latest
    outputs:
      exists_pr: ${{ steps.pr.outputs.exists }}
    steps:
      - name: Check PR
        id: pr
        uses: sogoagain/check-opened-pr-action@v0.1
  build:
    needs: check-pr
    if: github.event_name != 'push' || needs.check-pr.outputs.exists_pr == 'false'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test:coverage
      - name: Build
        run: npm run clean && npm run build
