name: CI - Pull request

on:
  pull_request:

concurrency:
  group: "build-pr-${{ github.head_ref }}"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - name: Check lint
        run: npm run lint
      - name: Tests
        run: npm run test:coverage
      - name: Build
        run: npm run clean && npm run build
